COMMON_RULES = """
### CAPITALIZATION
- **TV Text Capitalization**: Be aware that television graphics, banners, supers, etc., have some unique typographical conventions that don't always match the basics highlighted below. The biggest difference is the use of more initial capital letters in titles, job descriptions, etc. (Source: https://language-guide.cbcrc.ca/home/c/capitalization)
  *Negative Constraints*: former prime minister, high school principal
- **Proper Nouns and Generic Terms**: Names and other proper nouns need to be capitalized (the Rocky Mountains, Prime Minister Red Buttons), but generic terms (the mountains) and titles not followed by names (the prime minister) are generally kept lowercase. There are exceptions, however, including the King and the Governor General. (Source: https://language-guide.cbcrc.ca/home/c/capitalization)
  *Negative Constraints*: the mountains, the prime minister
- **Excessive Capitalization**: Too Many Capital Letters in Sentences become Distracting, including when a lot of abbreviations appear. So keep words lowercase unless you're sure capital letters apply. (Source: https://language-guide.cbcrc.ca/home/c/capitalization)
- **Company/Agency Titles**: Don't use capital letters for titles or events simply because some company or government agency does. (Source: https://language-guide.cbcrc.ca/home/c/capitalization)
- **General Capitalization Rule**: The rest of this page outlines the fundamentals of CBCNews.ca capitalization. In general, capitalize all: (Source: https://language-guide.cbcrc.ca/home/c/capitalization)
- **cities, provinces, territories**: Capitalize cities, provinces, territories as nouns on their own (Calgary, Ontario, Nunavut). (Source: https://language-guide.cbcrc.ca/home/c/capitalization)
- **countries**: Capitalize countries (Italy, Pakistan) and the terms for their citizens (Japanese). (Source: https://language-guide.cbcrc.ca/home/c/capitalization)
- **government departments, agencies, independent offices, regulatory watchdogs**: Capitalize government departments, agencies, independent offices, regulatory watchdogs, etc. (Health Canada, Department of Oceans and Fisheries, Alberta Fire Commissioner Office, Manitoba Advocate for Children and Youth, Ontario Labour Ministry, National Parole Service, Library of Parliament). (Source: https://language-guide.cbcrc.ca/home/c/capitalization)
- **legislation**: Capitalize legislation proposed (the Common Sense Firearms Licensing Act) and proclaimed (the Access to Information Act, the Copyright Act) when official titles are used. (Source: https://language-guide.cbcrc.ca/home/c/capitalization)
  *Negative Constraints*: mere descriptions of legislation (an act to toughen gun control), plural constructions (various human rights acts across the country)
- **musical compositions**: Capitalize principal words in English titles of musical compositions (Tchaikovsky's Symphony No. 4 in F minor). (Source: https://language-guide.cbcrc.ca/home/c/capitalization)
- **books, broadcast programs, poems, songs**: Capitalize principal words in English titles of books, broadcast programs, poems, songs, etc. (As It Happens, The World at Six, To Kill a Mockingbird). (Source: https://language-guide.cbcrc.ca/home/c/capitalization)
- **holidays, celebrations, special dates**: Capitalize national holidays, religious celebrations and some other special dates (Labour Day, Hanukkah, Education Week, New Year's Eve, April Fools' Day). (Source: https://language-guide.cbcrc.ca/home/c/capitalization)
  *Negative Constraints*: in the new year, election day
- **slogans, placards, posters, signs**: Capitalize slogans ('America First'), placards, posters and other signs ('Give Peace a Chance'), the titles of various parts of larger, published words, including newspaper headlines and book chapters, etc., even if the originals were primarily or entirely lowercase. Capitalize only the first letter... (Source: https://language-guide.cbcrc.ca/home/c/capitalization)
- **titles of creative works**: Capitalize titles of books, movies, songs, broadcast programs, etc., except for proper noun elements that are not considered principal words (e.g., As It Happens and A Star Is Born but The Nature of Things and The World at Six). (Source: https://language-guide.cbcrc.ca/home/c/capitalization)
- **official titles**: Capitalize official titles before names (Premier Howard Meeker; Minister of Health Kathy Needles). (Source: https://language-guide.cbcrc.ca/home/c/capitalization)
  *Negative Constraints*: titles after names (Meeker became premier two years ago; Needles, the minister of health; Harvest was appointed agriculture minister in 2008), job descriptions and their equivalents (special mediator, special prosecutor)
- **CBC.ca**: Refers to capitalization rules for 'the web', 'the internet', etc. (Source: https://language-guide.cbcrc.ca/home/c/capitalization)
- **Court versus court**: Refers to capitalization rules for 'Court' versus 'court'. (Source: https://language-guide.cbcrc.ca/home/c/capitalization)
- **Governor General**: Refers to capitalization rules for 'Governor General'. (Source: https://language-guide.cbcrc.ca/home/c/capitalization)
- **grain**: Refers to capitalization rules for 'grain'. (Source: https://language-guide.cbcrc.ca/home/c/capitalization)
- **Leader versus leader**: Refers to capitalization rules for 'Leader' versus 'leader'. (Source: https://language-guide.cbcrc.ca/home/c/capitalization)
- **military forces**: Refers to capitalization rules for military forces. (Source: https://language-guide.cbcrc.ca/home/c/capitalization)
- **military ranks**: Refers to capitalization rules for military ranks. (Source: https://language-guide.cbcrc.ca/home/c/capitalization)
- **Party versus party**: Refers to capitalization rules for 'Party' versus 'party'. (Source: https://language-guide.cbcrc.ca/home/c/capitalization)
- **police ranks**: Refers to capitalization rules for police ranks. (Source: https://language-guide.cbcrc.ca/home/c/capitalization)
- **quirky capitalization**: Follow specific capitalization for certain brands/terms (iPod, WikiLeaks, Visa, Adidas), respecting their established style. (Source: https://language-guide.cbcrc.ca/home/c/capitalization)
  *Negative Constraints*: VISA, adidas
- **Speaker**: Refers to capitalization rules for 'Speaker'. (Source: https://language-guide.cbcrc.ca/home/c/capitalization)
- **transliterations**: Follow specific capitalization rules for transliterated names (e.g., Al versus al in Arabic names). (Source: https://language-guide.cbcrc.ca/home/c/capitalization)
- **universities and colleges**: Refers to capitalization rules for universities and colleges. (Source: https://language-guide.cbcrc.ca/home/c/capitalization)
- **Titles (General)**: This page primarily focuses on typography, including how to handle titles before names versus titles on their own, and when to distinguish between formal titles (capitalized) and mere job descriptions (lowercase). (Source: https://language-guide.cbcrc.ca/home/t/titles)
- **TV Text**: Television graphics, banners, supers, etc., have unique typographical conventions. The biggest difference is the use of more initial capital letters in titles, job descriptions, etc. (e.g., 'Former Prime Minister' instead of former prime minister, and 'High School Principal' instead of high school p... (Source: https://language-guide.cbcrc.ca/home/t/titles)
- **Title Capitalization (General)**: Generally use capital letters for other currently held titles only when they appear immediately before a name. A few of these words are abbreviated (e.g., Coun. for councillor and Prof. for professor). (Source: https://language-guide.cbcrc.ca/home/t/titles)
- **police chief**: Capitalize when immediately before a name (e.g., Oz police Chief Red Buttons). Lowercase when after a name (e.g., Red Buttons, the police chief, said). (Source: https://language-guide.cbcrc.ca/home/t/titles)
- **Secondary Government Positions**: Although cabinet ministers' titles are capitalized before names, secondary (often informal) government positions are not. Example: Finance Minister Red Buttons but junior finance minister Red Buttons; Trade Minister Red Buttons but deputy trade minister Red Buttons. (Source: https://language-guide.cbcrc.ca/home/t/titles)
- **Long Titles**: When titles are particularly long (especially in the case of junior cabinet ministers), it's often helpful to recast the sentence to make the details easier for web readers to scan. (Source: https://language-guide.cbcrc.ca/home/t/titles)
- **shadow cabinet / shadow minister**: The expression 'shadow cabinet' is common and OK, especially in coverage of Canadian, British and other parliamentary systems. It refers to members of an opposition party designated as counterparts to government cabinet ministers. The narrower term 'shadow minister' requires care. As long as the mea... (Source: https://language-guide.cbcrc.ca/home/t/titles)
  *Negative Constraints*: be mindful of potential audience confusion and lean toward alternative wording (e.g., a given party's 'finance critic') when there's risk of ambiguity for 'shadow minister'
- **Foreign Leader Titles**: Include geographical modifiers in the titles of foreign leaders in first reference, regardless of the person's profile (e.g., U.S. President Donald Trump). (Source: https://language-guide.cbcrc.ca/home/t/titles)
  *Negative Constraints*: Avoid the American convention of leaving out 'past' or 'former' for previous office holders (e.g., our style is former U.S. president Bill Clinton)
- **Formal Titles vs. Job Descriptions**: Distinguish between formal titles and mere job descriptions (e.g., a company's president versus the person in the White House). A few positions are conventionally treated as titles before names (e.g., a judge versus a school principal). Abbreviations often mask what would otherwise be lowercase lett... (Source: https://language-guide.cbcrc.ca/home/t/titles)
- **Unique Offices and Temporary Appointments**: If an office is unique, capital letters are generally used when the title appears before the name (e.g., Privy Council Clerk Joseph Olivier Côté versus Appeal Court clerk Joe Coats). This includes top medical health officers across the country. If a position is unique but relatively junior, however,... (Source: https://language-guide.cbcrc.ca/home/t/titles)
- **Appeal Court clerk**: Lowercase when used as a relatively junior unique position before a name (e.g., Appeal Court clerk Red Buttons). (Source: https://language-guide.cbcrc.ca/home/t/titles)
- **Appeal Court Judge**: Capitalize when used as a formal title before a name (e.g., Appeal Court Judge Red Buttons). (Source: https://language-guide.cbcrc.ca/home/t/titles)
- **Apposition Latitude**: Appositives are common in journalism because they help convey key detail succinctly. CBC News style allows for geographical modifiers to be capitalized when part of a title before a name (e.g., German Chancellor Angela Merkel is fine). There's no need to prefer possessive forms when equally common a... (Source: https://language-guide.cbcrc.ca/home/t/titles)
  *Negative Constraints*: German chancellor Angela Merkel (not CBC style), Japan's prime minister Shinzo Abe (not CBC style), France's president Emmanuel Macron (not CBC style), Canada's chief public health officer Dr. Theresa Tam (not CBC style)
- **Possessive Titles**: Possessive forms are instantly perceived as titles, or proper title equivalents, which means there's no risk of confusion. Examples: Britain's Prime Minister Boris Johnson, Canada's Auditor General Sheila Fraser, Toronto's Medical Officer of Health Eileen de Villa. (Source: https://language-guide.cbcrc.ca/home/t/titles)
- **Temporary/Past Titles**: Do not use capital letters if people haven't been sworn in yet (U.S. president-elect), if they're just temporarily filling in ('acting prime minister' versus the proper title 'Deputy Prime Minister' or someone appointed on a longer, interim basis), if their designations are informal ('deputy premier... (Source: https://language-guide.cbcrc.ca/home/t/titles)
  *Negative Constraints*: Avoid the American convention of leaving out 'past' or 'former' for previous office holders (e.g., our style is former U.S. president Barack Obama)
- **Past vs. Present Titles**: When referring to past events, don't use terms such as former, ex-, the late, then, etc. Instead, use the year and then keep the title in uppercase. Example: On Jan. 26, 1976, Prime Minister Pierre Trudeau became the first Canadian leader to pay an official visit to Cuba. Although ex- is a good choi... (Source: https://language-guide.cbcrc.ca/home/t/titles)
  *Negative Constraints*: don't use terms such as former, ex-, the late, then, etc. when referring to past events
- **Royal Titles**: Canada's reigning monarch can usually be called the King or (depending on the story's context) the King of Canada. Adding a name is optional (King Charles or King Charles III). For other members of the Royal Family, use titles before first names (Prince William, Princess Beatrice). Titles are kept i... (Source: https://language-guide.cbcrc.ca/home/t/titles)
- **Knighthoods**: Knighthoods are chivalry honours and should generally be avoided in stories except in directly transcribed quotes. An exception is made for historical figures whose titles have become entrenched over time: Sir John A. Macdonald. This approach has nothing to do with minimizing the merit of a particul... (Source: https://language-guide.cbcrc.ca/home/t/titles)
  *Negative Constraints*: Elton John not Sir Elton John, Alfred Hitchcock not Sir Alfred Hitchcock, Elizabeth Taylor not Dame Elizabeth
- **Geographical abbreviations**: In first reference, most places need to be identified by more than their full name. We generally add the province, state, or territory for locations in North America, and the country for other spots in the world. This extra detail appears between commas. (Source: https://language-guide.cbcrc.ca/home/g/geography-cities)
- **Country name preferences**: The Language Guide lists CBC News preferences for the names of certain countries that are referred to in more than one way around the world. Always prefer English forms when these are entrenched. (Source: https://language-guide.cbcrc.ca/home/g/geography-cities)
  *Negative Constraints*: Côte d'Ivoire, Cabo Verde
- **Clipping official country names**: It's an acceptable convention to clip official names of countries, which can be much longer than what's commonly reported. (Source: https://language-guide.cbcrc.ca/home/g/geography-cities)
- **Accuracy in country names**: Even when countries have only one official name, care must be taken to avoid errors (e.g., mistakenly referring to Ukraine as 'the Ukraine'). (Source: https://language-guide.cbcrc.ca/home/g/geography-cities)
  *Negative Constraints*: the Ukraine
- **Distinguishing similar country names**: When two countries' names are very similar, it's important to distinguish between them to keep our journalism clear and accurate. Congo versus the Republic of Congo are examples. (Source: https://language-guide.cbcrc.ca/home/g/geography-cities)
- **Alternative geographical name spellings**: We normally use only one spelling or version of a proper noun in our journalism. But in rare cases, alternative forms of certain geographical names may be OK, depending on the context or the platform (e.g., St-Pierre-Miquelon, St-Pierre-et-Miquelon and Saint Pierre and Miquelon). (Source: https://language-guide.cbcrc.ca/home/g/geography-cities)
- **City spelling reference**: The National Geographic Atlas of the World is our main reference book for the spellings of communities outside of Canada. But in some cases we use widely accepted alternatives, so check this intranet site first. Some transliterations have changed in recent decades. (Source: https://language-guide.cbcrc.ca/home/g/geography-cities)
- **Clarity for foreign cities**: Always put the audience first. Therefore, if a story doesn't make the location obvious, it's generally best to add the name of the country. (Source: https://language-guide.cbcrc.ca/home/g/geography-cities)
- **Capitalization of Court Names**: Capitalize superior courts, courts of appeal, etc., but not generic lower court names. (Source: https://language-guide.cbcrc.ca/home/c/courts)
  *Negative Constraints*: not generic lower court names
- **Admiralty Court**: Capitalize. (Source: https://language-guide.cbcrc.ca/home/c/courts)
- **Appeal Court, Court of Appeal**: Capitalize. See also U.S. Court of Appeals below. (Source: https://language-guide.cbcrc.ca/home/c/courts)
- **Court of King’s Bench**: Capitalize. Use 'Court of Queen's Bench' in historical references. (Source: https://language-guide.cbcrc.ca/home/c/courts)
- **European Court of Justice**: Capitalize. (Source: https://language-guide.cbcrc.ca/home/c/courts)
- **family court**: Lowercase. (Source: https://language-guide.cbcrc.ca/home/c/courts)
- **Federal Court, Federal Appeal Court**: Capitalize. (Source: https://language-guide.cbcrc.ca/home/c/courts)
- **International Court of Justice**: Capitalize. (Source: https://language-guide.cbcrc.ca/home/c/courts)
- **Ontario provincial court**: Lowercase when generic descriptive label is used. (Source: https://language-guide.cbcrc.ca/home/c/courts)
- **Ontario Court of Justice**: Initial caps when unique, formal name of provincial court is used. (Source: https://language-guide.cbcrc.ca/home/c/courts)
- **Alberta's provincial court system**: Lowercase when generic descriptive label is used. (Source: https://language-guide.cbcrc.ca/home/c/courts)
- **Alberta Court of Justice**: Initial caps when unique, formal name of provincial court is used. (Source: https://language-guide.cbcrc.ca/home/c/courts)
- **the provincial court**: Lowercase. (Source: https://language-guide.cbcrc.ca/home/c/courts)
- **small claims court**: Lowercase. (Source: https://language-guide.cbcrc.ca/home/c/courts)
- **Superior Court (in Quebec)**: Capitalize. (Source: https://language-guide.cbcrc.ca/home/c/courts)
- **Superior Court of Justice (in Ontario)**: Capitalize. Commonly called the Ontario Superior Court. (Source: https://language-guide.cbcrc.ca/home/c/courts)
- **Yukon Supreme Court**: Capitalize. (Source: https://language-guide.cbcrc.ca/home/c/courts)
- **Supreme Court**: Capitalize (federal, provincial, or state), as in Supreme Court of Canada (SCC). (Source: https://language-guide.cbcrc.ca/home/c/courts)
- **Tax Court**: Capitalize (Canada and the U.S.). (Source: https://language-guide.cbcrc.ca/home/c/courts)
- **territorial court**: Lowercase (e.g., N.W.T., Yukon's territorial court). (Source: https://language-guide.cbcrc.ca/home/c/courts)
- **youth court**: Lowercase. (Source: https://language-guide.cbcrc.ca/home/c/courts)
- **Canadian Superior Courts Naming**: Superior courts in Canada go by different names depending on the province or territory (e.g., Saskatchewan Court of King's Bench, B.C. Supreme Court, Quebec Superior Court). (Source: https://language-guide.cbcrc.ca/home/c/courts)
- **Lowercase in general references**: Use lowercase for general references to court-related terms. (Source: https://language-guide.cbcrc.ca/home/c/courts)
- **the court**: Lowercase when used in general references like 'the court ordered' or 'the court was told'. (Source: https://language-guide.cbcrc.ca/home/c/courts)
- **the provincial court judge**: Lowercase. (Source: https://language-guide.cbcrc.ca/home/c/courts)
- **Avoid confusing names of courts of appeal (Canada)**: In Canada, refer to the highest court within a given province or territory as an appeal court (e.g., Alberta Court of Appeal). Simplify longer forms (e.g., Newfoundland and Labrador Court of Appeal). (Source: https://language-guide.cbcrc.ca/home/c/courts)
  *Negative Constraints*: Be cautious with historical references, since some proper nouns are no longer used (e.g., the Ontario Court of Appeal was previously called the Supreme Court of Ontario)., Do not abbreviate Supreme Court of Canada as SCOC.
- **Alberta Court of Appeal**: Refer to the highest court within a given province or territory as an appeal court. (Source: https://language-guide.cbcrc.ca/home/c/courts)
- **Newfoundland and Labrador Court of Appeal**: Can be used to simplify longer official names. (Source: https://language-guide.cbcrc.ca/home/c/courts)
- **Federal Court of Appeal**: A common noun for a Canadian court of appeal. (Source: https://language-guide.cbcrc.ca/home/c/courts)
- **Supreme Court of Canada**: A common noun for a Canadian court of appeal. Abbreviated as SCC. (Source: https://language-guide.cbcrc.ca/home/c/courts)
  *Negative Constraints*: not SCOC
- **Court of Appeals (U.S.) - Proper Nouns**: For proper nouns (with initial caps) in the U.S., match official names. (Source: https://language-guide.cbcrc.ca/home/c/courts)
- **the U.S. Court of Appeals for the 7th Circuit**: Capitalize as it is an official name. (Source: https://language-guide.cbcrc.ca/home/c/courts)
- **U.S. Court of Appeals**: Acceptable when reporting on a specific circuit's court in the U.S. (There are 11 of them). (Source: https://language-guide.cbcrc.ca/home/c/courts)
- **Court of Appeals (U.S.) - Generic References**: For generic references, lowercase 'appeal' and 'appeals' are both acceptable, but it's best to be consistent within a story. (Source: https://language-guide.cbcrc.ca/home/c/courts)
- **a U.S. federal court of appeals**: Lowercase for generic reference. (Source: https://language-guide.cbcrc.ca/home/c/courts)
- **a U.S. appeals court**: Lowercase for generic reference. (Source: https://language-guide.cbcrc.ca/home/c/courts)
- **an appeal court or an appeals court**: Lowercase for generic reference; consistency advised. (Source: https://language-guide.cbcrc.ca/home/c/courts)


### PUNCTUATION


### NUMBERS
- **Lowercase names (from dollars to bitcoins)**: Keep the names of currencies lowercase (dollars, pounds, yen, kronor), even when they're based on a proper noun element (e.g., euros from Europe). This applies to cryptocurrencies, such as bitcoin, virtual money, such as various online gaming credits, and promotional coupons and store vouchers (25 c... (Source: https://language-guide.cbcrc.ca/home/m/money)
- **Generally prefer Canadian dollars**: Unless there's a strong editorial reason to refer to a foreign currency, report virtually all monetary amounts in Canadian dollars. The four most common exceptions: 1. When a story focuses on the United States, it's often easiest to present all figures in U.S. dollars. See conversions for more detai... (Source: https://language-guide.cbcrc.ca/home/m/money)
- **Use figures: $7, $60,000, $1 million**: In online journalism, use figures not words like "thousand" or "hundred thousand" for amounts up to $999,999 that include currency symbols. Avoid broadcast constructions full of hyphens, such as one-hundred-and-thirty-five-thousand dollars: $7, $123.50, $60,000, $135,000, $1 million, $12 billion. Wh... (Source: https://language-guide.cbcrc.ca/home/m/money)
  *Negative Constraints*: Avoid broadcast constructions full of hyphens, such as one-hundred-and-thirty-five-thousand dollars, Do not use unfamiliar terms, such as 'quintillion' or even 'quadrillion.'
- **Money in headlines**: In web headlines, thousand (K), million (M), billion (B) and trillion (T) can be abbreviated when referring to money. There is no space between the the currency sign ($, €), the number and the uppercase letter: $13K, $175M, €25B, $3T. The $ implies Canadian currency unless otherwise specified. Somet... (Source: https://language-guide.cbcrc.ca/home/m/money)
  *Negative Constraints*: Avoid more obscure currency symbols, such as ¥ for yen and ₣ for franc
- **Limit hyphens to adjectives before nouns**: Some news organizations use hyphens in routine currency constructions to avoid any possible confusion (e.g., $100 million would always be reported as $100-million to avoid any possible misreading of the amount as '$100' during a quick scan). But this is not a standard publishing convention, is not t... (Source: https://language-guide.cbcrc.ca/home/m/money)
- **The $ sign**: Use figures next to the $ sign (or other acceptable currency symbols as outlined below), even for numbers below 10: They printed one million tickets, which sold for $5 a piece. The prize was $1 million. Generally use the currency sign ($) instead of writing out 'dollar.' While small amounts are some... (Source: https://language-guide.cbcrc.ca/home/m/money)
- **Conversions**: Many countries call their monetary units 'dollars,' including Antigua, Australia, Fiji, Guyana, Hong Kong, Namibia, New Zealand and Tuvalu. But instead of writing '$120 million (Australian),' we generally convert the figure into Canadian dollars ('$117 million'). The Bank of Canada's website feature... (Source: https://language-guide.cbcrc.ca/home/m/money)
- **Cdn, US (no periods)**: In our news stories, Canadian dollars are normally implied. But if the context is not clear (e.g., in stories that refer to different countries' currencies), specify 'Canadian.' In web journalism, this means adding the abbreviation 'Cdn' after the figure. Indicate American dollars by putting 'US' af... (Source: https://language-guide.cbcrc.ca/home/m/money)
  *Negative Constraints*: Do not include periods in Cdn or US when identifying the country's money, except at the end of a sentence, Do not include hyphens before the currency notation (US or Cdn) in adjectival constructions, Never abbreviate Canada or Canadian outside of the currency designation 'Cdn' noted above, even in headlines
- **Pounds (£), euros (€), yen, pesos, kronor, etc.**: When a currency is volatile or if the original figures are extremely large (e.g., a country's debt) and even slight fluctuations can be significant during a brief period, it's often preferable to report the figure in the original currency first — with the most up-to-date Canadian dollar conversions ... (Source: https://language-guide.cbcrc.ca/home/m/money)
  *Negative Constraints*: For the most part, we avoid foreign currency symbols (e.g., ¥ for yen or ₣ for franc), even in headlines, avoid using either abbreviation (GBP or UKP)
- **A note about euros**: Since Jan. 1, 2002, the euro has been used as a common currency in more than 10 European countries, including Austria, Belgium, Finland, France, Germany, Greece and Italy. The names of some well-known monetary units — such as francs and lire — are still active in other parts of the world, however, s... (Source: https://language-guide.cbcrc.ca/home/m/money)


### SPELLING & HYPHENS
- **Canadian Spelling Preferences**: Canadians use a blend of British (e.g., 'cheque' not 'check') and North American (e.g., 'tire' not 'tyre') spellings. Some preferences are common (e.g., 'plow' and 'axe' instead of 'plough' and 'ax'), while other words are frequently written in more than one way (e.g., 'acknowledgement' and 'acknowl... (Source: https://language-guide.cbcrc.ca/home/s/spelling)
- **Modified Canadian Press Style**: Follow a modified Canadian Press style. Guidelines include retaining the 'u' in many 'our' endings (colour, labour, favour), doubling the 'l' before many suffixes (carolling, labelling, signalling, travelling), dropping the 'muted e' when adding 'able' to certain words (likable, movable, sizable), a... (Source: https://language-guide.cbcrc.ca/home/s/spelling)
- **Spelling Assumption**: Never assume a spelling. For instance, 'vapour' and 'honour' both have a 'u,' but 'vaporize' and 'honorary' do not. Generally follow the official spelling of a proper noun in English (e.g., the 'World Trade Center', not 'Centre'), with an exception for U.S. government departments. (Source: https://language-guide.cbcrc.ca/home/s/spelling)
  *Negative Constraints*: assume a spelling
- **Canadian Geographical Names**: For Canadian place names (cities, towns, villages, lakes, rivers), consult the Canadian Geographical Names Database published by Natural Resources Canada. For provincial name context, see 'provinces and cities'. (Source: https://language-guide.cbcrc.ca/home/s/spelling)
- **Geographical Transliterations**: Be aware that preferred transliterations have changed since the breakup of the Soviet Union (e.g., 'Chornobyl' and 'Kyiv' instead of 'Chernobyl' or 'Kiev', based on Ukrainian rather than Russian). See 'cities around the world' and 'transliterations' overview. (Source: https://language-guide.cbcrc.ca/home/s/spelling)
- **National Geographic Atlas**: The National Geographic Atlas of the World can be helpful, but always check the CBC Language Guide for spelling exceptions (e.g., 'Athens', 'Copenhagen', 'Munich', 'Nuremberg', 'Taipei', 'Venice', 'Warsaw' based on established English convention). For country name context, see 'cities around the wor... (Source: https://language-guide.cbcrc.ca/home/s/spelling)
- **Canadian Spelling Preference (Ligatures)**: Canadian media frequently, but not always, go with the shorter spellings common in the U.S. for optional ligatures, contrasting with British media which tend to embrace them. (Source: https://language-guide.cbcrc.ca/home/s/spelling/lingering-ligatures)
- **archaeology**: Preferred spelling. This 'ae' spelling differs from CP style and was adopted by CBC News in November 2022 after public feedback from academics who stressed that most archaeologists in North America still use the ligature. It is found at virtually all Canadian universities and Parks Canada heritage s... (Source: https://language-guide.cbcrc.ca/home/s/spelling/lingering-ligatures)
  *Negative Constraints*: archeology
- **Canadian Spelling Characteristics**: Canadian spelling lacks a consistent pattern, with choices between American and British forms varying by word, context, publication, genre, region, and social group. (Source: https://language-guide.cbcrc.ca/home/s/spelling/lingering-ligatures)
- **Modified CP Style**: CBC News picked the Canadian Press Stylebook as its primary reference manual for typography (spelling, capitalization, punctuation, etc.) in the late 1990s. Although CBC has since established its own publishing style, CP remains a major influence. CBC follows a modified CP style when publishing text... (Source: https://language-guide.cbcrc.ca/home/s/spelling/modified-cp-style)
- **Sept. 11**: CP described it as an acceptable term to refer to the 'day of terrorist attacks in the United States.' CBC News does not call these 'terrorist attacks' without attribution. (Source: https://language-guide.cbcrc.ca/home/s/spelling/modified-cp-style)
  *Negative Constraints*: do not call 'terrorist attacks' without attribution
- **CP Outdatedness**: CP's manual can be slow to update names and titles. Examples include BCE Inc. to Bell Canada Inc., 'Guinness Book of Records' to 'Guinness World Records', and Tsuut'ina Nation's revised spelling. CBCNews.ca adopts changes immediately. (Source: https://language-guide.cbcrc.ca/home/s/spelling/modified-cp-style)
- **Disagreement with CP Choices**: CBC News reserves the right to disagree with CP's stylistic choices, often preferring simpler or audience-friendly options. Examples include capitalization of tech brands, shorthand for Sept. 11, placement of 'Cardinal' title, and spelling of 'archeology'. (Source: https://language-guide.cbcrc.ca/home/s/spelling/modified-cp-style)
- **Adherence to CP Preferences**: CBC frequently consults the Canadian Press Stylebook, Canadian Oxford Dictionary, Canadian Permanent Committee on Geographical Names, and National Geographic Atlas of the World. CBC resists abandoning CP preferences on a whim to maintain consistent style, but reserves the freedom to take its own pat... (Source: https://language-guide.cbcrc.ca/home/s/spelling/modified-cp-style)
  *Negative Constraints*: resist abandoning CP preferences on a whim
- **currency construction (e.g., US$550 vs $550 US)**: CBC rejects CP's move to 'US$550' from '$550 US' because the fused construction is harder to read on the web, preferring the latter for audience clarity. (Source: https://language-guide.cbcrc.ca/home/s/spelling/modified-cp-style)
  *Negative Constraints*: not 'US$550'
- **Colour versus color**: In the case of proper nouns, generally adopt the original spelling (e.g., Technicolor, The Color Purple, the National Association for the Advancement of Colored People). See 'defence, labour and centre' for exceptions. (Source: https://language-guide.cbcrc.ca/home/s/spelling/our)


### DATES & TIME
- **Specify local time**: Since stories written by CBC journalists in different parts of the country may be read, watched or heard by people outside of a specific province or territory, one of Canada's seven time zones should be specified when clock readings are included in editorial content. On air, this is often done by us... (Source: https://language-guide.cbcrc.ca/home/t/time)
- **Saskatchewan Time Zone**: To ensure accuracy and clarity, use CST in all Saskatchewan clock readings. Saskatchewan as a whole can be accurately described as being on CST 12 months of the year. Even though CST = MDT between mid-March and early November, never imply that Saskatchewan actually shifts to mountain time. When repo... (Source: https://language-guide.cbcrc.ca/home/t/time)
  *Negative Constraints*: never imply that Saskatchewan actually shifts to mountain time
- **Clock Readings Abbreviation**: The terms a.m. and p.m. are always lowercase with periods. Use colons to separate hours and minutes (2:01 p.m. NT). But leave out colons in all top-of-the-clock readings (2 p.m. NT, not 2:00 NT). In digital publishing, generally repeat a.m. and p.m. in time ranges for clarity (e.g., 8 a.m. to 11 a.m... (Source: https://language-guide.cbcrc.ca/home/t/time)
  *Negative Constraints*: not 2:00 NT, avoid adding conjunctions when spelling out duration abbreviations (e.g., His time was two hours 38 minutes 40.7 seconds)
- **Greenwich Mean Time (GMT)**: When converting clock readings from overseas, keep in mind that Greenwich mean time (GMT) is five hours ahead of eastern standard time (during Canada's fall and winter), and four hours ahead of eastern daylight time (during Canada's spring and summer). Although Greenwich mean time (GMT) stays the sa... (Source: https://language-guide.cbcrc.ca/home/t/time)
- **Dating Stories**: As today becomes yesterday tomorrow, it's almost impossible for editors and writers to find and change every dated reference that may be hiding in someone else's copy. There's value in the immediacy of certain phrasing (e.g., 'The plane will try an emergency landing in the next few minutes' and 'The... (Source: https://language-guide.cbcrc.ca/home/t/time)
  *Negative Constraints*: be careful when using terms like 'this morning' or 'today' or 'last night' in our online journalism, avoid redundancies (e.g., write '4:15 p.m. Thursday,' not '4:15 p.m. Thursday afternoon.'), avoid contradictory terms like 'at about.' Pick one. It either happened at 4:15 p.m. or it happened about (or around) 4:15 p.m., but not at about.
- **Decades (Formatting)**: Prefer figures to label decades: the 1930s, the '30s (instead of the Thirties), the Dirty '30s. Exceptions are certain entrenched names treated as proper nouns (e.g., the '60s but the Sixties Scoop). Do not put apostrophes before the 's' in the plural forms of years (1980s, 1920s, mid-1940s). Also, ... (Source: https://language-guide.cbcrc.ca/home/t/time)
  *Negative Constraints*: do not put apostrophes before the 's' in the plural forms of years, not with 'early' or 'late' (for hyphens), not when referring to an official name that doesn't include the punctuation (for abbreviated years with apostrophes)
- **Months (Formatting)**: For guidelines on months (March 15 versus Aug. 12, etc.), see abbreviations. (Source: https://language-guide.cbcrc.ca/home/t/time)


### PLACES & MISC
- **Provincial/Territorial Abbreviation (General)**: Do not abbreviate provincial or territorial names unless they appear after cities, towns or other communities in the body of a story, with the exception of British Columbia (B.C.), Prince Edward Island (P.E.I.) and the Northwest Territories (N.W.T.). (Source: https://language-guide.cbcrc.ca/home/p/provinces-and-cities)
  *Negative Constraints*: do not abbreviate provincial or territorial names (unless after cities/towns or for B.C., P.E.I., N.W.T.)
- **City, Town, Village Capitalization**: Generic words like 'city', 'town', and 'village' are generally lowercase, unless referring to the proper legal name of a community (e.g., 'the City of Calgary'). (Source: https://language-guide.cbcrc.ca/home/p/provinces-and-cities)
- **International Place Name Spellings**: For communities outside Canada, rely on the National Geographic Atlas of the World, but check the Language Guide for exceptions (e.g., Bangkok, Dunkirk, Taipei, Rome). (Source: https://language-guide.cbcrc.ca/home/p/provinces-and-cities)
- **United States, U.S., US**: General guidance for using 'United States', 'U.S.', and 'US', including when to use periods, when to add 'U.S.' to otherwise ambiguous names/titles, and notes on state abbreviations and standalone cities. (Source: https://language-guide.cbcrc.ca/home/u/united-states)
- **United States / U.S. (preference)**: Prefer 'United States' or 'the U.S.' over 'United States of America' or 'the U.S.A.'. (Source: https://language-guide.cbcrc.ca/home/u/united-states)
  *Negative Constraints*: not 'United States of America', not 'U.S.A.'
- **U.S. (periods)**: Use periods in 'U.S.' except when referring to currency (e.g., '$300 US'). (Source: https://language-guide.cbcrc.ca/home/u/united-states)
  *Negative Constraints*: do not use periods in 'US' when referring to currency
- **American (adjective)**: Use 'American' as an adjective for people and things generally (e.g., 'American city', 'American scientist'). For more formal references to the country or government, use 'U.S.' (e.g., 'U.S. Embassy', 'U.S. trade representative'). (Source: https://language-guide.cbcrc.ca/home/u/united-states)
- **U.S. Government Departments/Agencies**: Add 'U.S.' to the names of most government departments, agencies, and organizations in first reference (e.g., 'U.S. State Department'), unless the proper noun is instantly recognized (e.g., NASA, NSA, FBI, CIA). This practice extends to spelled-out popular short forms (e.g., 'U.S. National Aeronauti... (Source: https://language-guide.cbcrc.ca/home/u/united-states)
- **U.S. Federal Politicians**: Add 'U.S.' to the titles of most federal politicians in first reference (e.g., 'U.S. President Donald Trump'). In second reference, the name or abbreviated title is sufficient. Avoid mirroring American news organizations' style of dropping 'U.S.' from titles, as CBC News style requires locators for ... (Source: https://language-guide.cbcrc.ca/home/u/united-states)
  *Negative Constraints*: avoid mirroring American news organizations' style of dropping 'U.S.' from titles of U.S. politicians
- **U.S. State Abbreviations (list)**: Standard abbreviations for U.S. states: Ala. (Alabama), Ariz. (Arizona), Ark. (Arkansas), Calif. (California), Colo. (Colorado), Conn. (Connecticut), Del. (Delaware), Fla. (Florida), Ga. (Georgia), Ill. (Illinois), Ind. (Indiana), Kan. (Kansas), Ky. (Kentucky), La. (Louisiana), Md. (Maryland), Mass.... (Source: https://language-guide.cbcrc.ca/home/u/united-states)
- **U.S. States Not to Abbreviate**: Do not abbreviate the following U.S. states or associated territories: Alaska, Hawaii, Idaho, Iowa, Maine, Ohio, Texas, Utah, Puerto Rico, Virgin Islands. (Source: https://language-guide.cbcrc.ca/home/u/united-states)
  *Negative Constraints*: do not abbreviate Alaska, do not abbreviate Hawaii, do not abbreviate Idaho, do not abbreviate Iowa, do not abbreviate Maine, do not abbreviate Ohio, do not abbreviate Texas, do not abbreviate Utah, do not abbreviate Puerto Rico, do not abbreviate Virgin Islands
- **Shortened Forms (U.S. states)**: Shortened forms of U.S. states are generally not used except in headlines and after the names of most communities (e.g., 'Great Falls, Mont.'). (Source: https://language-guide.cbcrc.ca/home/u/united-states)
  *Negative Constraints*: do not use shortened forms of U.S. states except in headlines and after community names
- **Two-Character Postal Abbreviations (U.S. states)**: Two-character postal abbreviations (e.g., AB for Alabama, MA for Massachusetts) are restricted to maps, graphics, and similar contexts with severe space constraints. (Source: https://language-guide.cbcrc.ca/home/u/united-states)
  *Negative Constraints*: do not use two-character postal abbreviations (e.g., AB, MA) outside of maps, graphics, etc.
- **U.S. Cities (Standalone)**: A list of well-known U.S. cities that can stand alone on first reference without geographical abbreviations: Atlanta, Baltimore, Boston, Chicago, Cincinnati, Cleveland, Dallas, Denver, Detroit, Honolulu, Houston, Indianapolis, Las Vegas, Los Angeles, Miami, Milwaukee, Minneapolis, Nashville, New Orl... (Source: https://language-guide.cbcrc.ca/home/u/united-states)
  *Negative Constraints*: do not put geographical abbreviations (state or district) after the listed standalone cities
- **The versus the**: Provides guidelines for the capitalization and usage of the definite article 'the' in various contexts, including titles, geographical names, nicknames, organizations, and abbreviations. (Source: https://language-guide.cbcrc.ca/home/t/the-versus-the)
- **Using 'The' in titles**: Capitalize 'The' when it begins the title of a book (unless it's a dictionary, encyclopedia or other reference publication), movie, television or radio program, song, magazine (unless it's a scholarly journal or other reference periodical), painting, sculpture or other composition. (Source: https://language-guide.cbcrc.ca/home/t/the-versus-the)
  *Negative Constraints*: Do not capitalize 'the' if it's not in the actual title (e.g., 'the Mona Lisa'), Do not italicize magazine titles (e.g., 'The New Yorker')
- **Using 'the' in miscellaneous contexts**: Keep 'the' lowercase in almost all other contexts, including at the start of almanacs, academic journals, directories, dictionaries, encyclopedias, handbooks, newspapers, holy books, most buildings, companies, ships, trains, music groups, awards, sports events, etc. Rare exceptions are generally bas... (Source: https://language-guide.cbcrc.ca/home/t/the-versus-the)
- **Using 'the' with abbreviations**: Although it's common to put 'the' in front of many abbreviations that represent organizations (e.g., the UN, the RCMP), this convention is often dropped with well-known acronyms. (Source: https://language-guide.cbcrc.ca/home/t/the-versus-the)
  *Negative Constraints*: Do not use 'the NATO', Do not use 'the NASA', Do not use 'the OPEC', NEVER use 'the HMCS'
- **United Nations (UN) Usage**: The United Nations should be spelled out in first reference, although UN is fine in headlines. CBC News style is UN without punctuation. (Source: https://language-guide.cbcrc.ca/home/u/united-nations)
  *Negative Constraints*: avoid periods with UN
- **UN General Assembly**: Use 'the General Assembly' or 'the Assembly' on second reference. (Source: https://language-guide.cbcrc.ca/home/u/united-nations)
- **UN Secretary General**: Use 'the secretary general' on second reference. (See also -general) (Source: https://language-guide.cbcrc.ca/home/u/united-nations)
- **UN Security Council**: Use 'the Security Council' on second reference. (Source: https://language-guide.cbcrc.ca/home/u/united-nations)
- **International Court of Justice**: No abbreviation. (Source: https://language-guide.cbcrc.ca/home/u/united-nations)
  *Negative Constraints*: No abbreviation
- **UNICEF**: Fine in first reference, but define as the 'United Nations Children's Fund' at some point in story. It's no longer called 'the UN International Children's Emergency Fund,' even though the old abbreviation is still used. (Source: https://language-guide.cbcrc.ca/home/u/united-nations)
  *Negative Constraints*: not 'the UN International Children's Emergency Fund'
- **UN High Commissioner for Refugees**:  (Source: https://language-guide.cbcrc.ca/home/u/united-nations)
- **World Health Organization**: WHO OK in headlines and second reference. There's usually no need to use a definite article before the abbreviation — i.e., make it 'according to WHO' rather than 'according to the WHO' — based on convention. Be aware, however, that WHO on its own can sometimes sound more like a pronoun ('who') than... (Source: https://language-guide.cbcrc.ca/home/u/united-nations)
  *Negative Constraints*: not 'the WHO' (unless for clarity in broadcast scripts)
- **King and Queen (heads of state)**: Use king and queen when referring to heads of state. The titles are capitalized before names. But in generic second references, the nouns are lowercase except for Canada's sovereign and former British monarchs. Examples: the King (Canada's monarch), King Carl XVI Gustaf of Sweden, the king (foreign ... (Source: https://language-guide.cbcrc.ca/home/r/royal-titles)
- **Royals and Surnames**: Royals rarely use surnames. When titles have been inherited or bestowed, they’re generally needed to help identify people (e.g., prince and princess for the children and certain grandchildren of monarchs, duke and duchess for the spouses of some royals). These titles are not capitalized, however, un... (Source: https://language-guide.cbcrc.ca/home/r/royal-titles)
  *Negative Constraints*: Prince Harry is a prince not a Prince
- **Formal Titles and Royal Rankings**: Limit use of formal titles to keep coverage uncluttered and understandable (e.g., prefer Princess Beatrice over 'Princess Beatrice of York' as long as the context makes it clear she's Prince Andrew's daughter). Leave out royal rankings (e.g., HIH for Her/His Imperial Highness, HRH for Her/His Royal ... (Source: https://language-guide.cbcrc.ca/home/r/royal-titles)
  *Negative Constraints*: Limit use of formal titles, Leave out royal rankings, Don't use HRH unless you're sure
- **Capitalization Rules (Online Journalism)**: The capitalization rules outlined apply to online journalism. They're based on long-standing publishing conventions. Different style is acceptable in TV supers and graphics, however, depending on relevant in-house guidelines. (Source: https://language-guide.cbcrc.ca/home/r/royal-titles)
- **Charles's (possessive)**: The possessive of Charles is Charles's, as in Charles's reign, Charles's speech, Charles's sons. (Source: https://language-guide.cbcrc.ca/home/r/royal-titles)
- **Catherine (Princess of Wales)**: In first and subsequent references, William's wife is called: Catherine (as in William and Catherine), the Princess of Wales, Catherine Middleton (acceptable convention in some contexts), Kate (OK sometimes, but informal so use sparingly). After she became the Princess of Wales in the fall of 2022, ... (Source: https://language-guide.cbcrc.ca/home/r/royal-titles)
  *Negative Constraints*: There is no need to use any of Catherine's other titles, such as the Duchess of Cornwall and Cambridge, or the Countess of Strathearn and Baroness Carrickfergus
- **Prince Harry (first reference)**: In first reference, Charles's youngest son can be called: Prince Harry (preferred; virtually no one has called him by his formal name, 'Prince Henry,' since his birth in 1984), the Duke of Sussex (a title granted on his wedding in 2018). There's no need to call him the Duke of Sussex unless the deta... (Source: https://language-guide.cbcrc.ca/home/r/royal-titles)
  *Negative Constraints*: There's no need to call him the Duke of Sussex unless the detail is relevant to the story or the title is considered the simplest way to introduce Harry and his wife
- **Prince Archie, Princess Lilibet**: Harry and Meghan's children are: Prince Archie Mountbatten-Windsor (born in May 2019), Princess Lilibet Mountbatten-Windsor (born in June 2021). As grandchildren of a reigning King, the titles prince and princess were expected to be automatically granted to Harry's children when Queen Elizabeth died... (Source: https://language-guide.cbcrc.ca/home/r/royal-titles)
  *Negative Constraints*: There's no need to add the prepositional detail 'of Sussex' after their names (e.g., Prince Archie of Sussex)
- **Harry and Meghan's HRH Status**: Effective April 1, 2020, Harry and Meghan officially stopped representing the Queen at public events, and stopped using their 'HRH' (His/Her Royal Highness) honorifics. Their other titles remain in place, however, which means it's OK to continue to call him Prince Harry, and to use the proper nouns ... (Source: https://language-guide.cbcrc.ca/home/r/royal-titles)
- **Queen Elizabeth (Longest-serving monarch)**: Elizabeth was indisputably the longest-serving sovereign in British history (just over 70 years and seven months on the throne). Some historians also argue that she was 'effectively' the longest-serving monarch in world history. (Source: https://language-guide.cbcrc.ca/home/r/royal-titles)
- **Children's titles (Prince/Princess of Wales)**: If the Prince of Wales has sons or daughters, the children's titles are technically tied to the father's on paper (e.g., Prince George of Wales, Princess Charlotte of Wales) but not in practice (i.e., we simply refer to Prince George and Princess Charlotte). The official title of the wife counterint... (Source: https://language-guide.cbcrc.ca/home/r/royal-titles)
  *Negative Constraints*: Such forms are never used in news stories
- **Princess Diana / Princess Di (usage)**: She is commonly remembered as 'Princess Diana' or 'Princess Di' based on popular but incorrect rewording of the title she held while married to Charles. Diana was not actually a princess. Since her death, however, the compounds Princess Diana and Princess Di have become the norm. It's OK to use the ... (Source: https://language-guide.cbcrc.ca/home/r/royal-titles)
  *Negative Constraints*: Avoid generic references to her as 'a princess' in stories
- **Capitalization of 'Royal Family' (foreign)**: Use capital letters only for the Canadian sovereign's family: the Royal Family. All other royal families are lowercase (e.g., Sweden's royal family, the Danish royal family). (Source: https://language-guide.cbcrc.ca/home/r/royal-titles)
- **Capitalization of Foreign Royal Titles**: The titles king, queen, prince and princess are capitalized only in front of the names of living members of foreign royal families (e.g., King Albert II of Belgium but Belgium's king; Queen Sofia of Spain but the king and queen of Spain, Spain's queen consort; the former queen Astrid of Belgium). (Source: https://language-guide.cbcrc.ca/home/r/royal-titles)
- **royal (adjective)**: The word royal is virtually always lowercase (royal assent, royal proclamation, royal residences, royal salute, royal tour, royal wedding, royalty) unless part of a proper noun (Royal Canadian Mounted Police, Royal Ontario Museum, Royal Newfoundland Constabulary). The primary exception is Royal Fami... (Source: https://language-guide.cbcrc.ca/home/r/royal-titles)
- **Ordinals for Other Titles**: Ordinals are not normally used for other titles unless the detail helps our audience understand the story better (e.g., Diana's brother Charles can be called the Earl Spencer rather than the 9th Early Spencer as long as overall context makes his identity clear). (Source: https://language-guide.cbcrc.ca/home/r/royal-titles)
- **Superfluous Titles**: Avoid superfluous titles unless there's obvious editorial merit. For example, before Charles became the King in 2022, there was generally no need to refer to him as the Duke of Cornwall, a title he'd held since the age of 4. The most common exceptions were when the detail was relevant to a given sto... (Source: https://language-guide.cbcrc.ca/home/r/royal-titles)
  *Negative Constraints*: Avoid superfluous titles unless there's obvious editorial merit
- **Formal Titles (Marquess, Viscount)**: Don't stuff stories with formal titles (e.g., marquess and marchioness, viscount and viscountess). Instead, prefer simpler language — as long as its accurate and clear (e.g., Lord Bristol or Lady Bath rather than Marquess of Bristol and the Marchioness of Bath). (Source: https://language-guide.cbcrc.ca/home/r/royal-titles)
  *Negative Constraints*: Don't stuff stories with formal titles
- **Life Peerages**: Life peerages (titles that are not hereditary) should be used only if relevant to the story. The most common life peerage granted by the Crown is baron. In these cases, type in the full title: Lord Black of Crossharbour (Lord Black in second reference). Otherwise, stick to the name that's more famil... (Source: https://language-guide.cbcrc.ca/home/r/royal-titles)
- **Knighthood-related Honorifics ('Sir', 'Dame')**: Generally avoid knighthood-related honorifics 'Sir' and 'Dame' (e.g. Alfred Hitchcock, not 'Sir Alfred Hitchcock,' Elizabeth Taylor, not 'Dame Elizabeth') unless referring to historical figures whose titles have become entrenched over time (e.g., Sir John A. Macdonald). These chivalry addresses are ... (Source: https://language-guide.cbcrc.ca/home/r/royal-titles)
  *Negative Constraints*: Generally avoid knighthood-related honorifics 'Sir' and 'Dame'
- **TV Text Reminder**: Be aware that television graphics, banners, supers, etc., have some unique typographical conventions. The biggest difference is the use of more initial capital letters in titles, job descriptions, etc. (e.g., "Former Prime Minister" instead of former prime minister, and "High School Principal" inste... (Source: https://language-guide.cbcrc.ca/home/m/military-ranks)
- **Military Rank Abbreviations**: Use abbreviations for military ranks only before names and if the rank is currently held. Abbreviated forms are always capitalized. (Source: https://language-guide.cbcrc.ca/home/m/military-ranks)
- **Non-Abbreviated Military Ranks**: Some military ranks do not have abbreviations and are written in full. The first letter is capitalized unless the position is no longer held (e.g., Admiral Jim Smith, Vice-Admiral Harold). (Source: https://language-guide.cbcrc.ca/home/m/military-ranks)
- **Military Ranks Without Names**: Write out military ranks or titles in full when used without names (e.g., "The lieutenant-colonel signed the documents.", "The general talked to reporters."). (Source: https://language-guide.cbcrc.ca/home/m/military-ranks)
- **Navy Captain and Lieutenant Ranks**: The ranks of captain and lieutenant are higher in the navy than in the army and air force. To acknowledge this, use 'navy' (lowercase) before the abbreviation (e.g., 'navy Capt. Ruth Oikawa', 'navy Lt.'). This approach is preferred over the CAF's use of a capital 'N' in brackets for clarity in broad... (Source: https://language-guide.cbcrc.ca/home/m/military-ranks)
- **Verifying Military Ranks**: If unsure about military ranks or roles, ask the individual or contact a Canadian Forces spokesperson. (Source: https://language-guide.cbcrc.ca/home/m/military-ranks)
- **Former Military Titles**: Former military titles are always lowercase. (Source: https://language-guide.cbcrc.ca/home/m/military-ranks)
- **police versus police**: Keep the generic word 'police' lowercase, except when it is part of a formal name. Examples of formal names include Royal Canadian Mounted Police, Ontario Provincial Police, Frederitcon Police Force, Halifax Regional Police, Vancouver Police Department, Calgary Police Service, and Toronto Police Ser... (Source: https://language-guide.cbcrc.ca/home/p/police-forces)
- **force (generic use)**: It is generally acceptable to use the lowercase noun 'force' as a synonym for service, department, etc., in generic references (e.g., Vancouver's police force to mean the Vancouver Police Department). Context and a given story's tone can influence word choice. 'Force' directly conveys the sense of l... (Source: https://language-guide.cbcrc.ca/home/p/police-forces)
- **Police force abbreviations**: With the exception of well-known initialisms such as the RCMP, generally avoid abbreviating the names of police forces in national stories. For less common abbreviations like CPD (Chicago Police Department), use conversational alternatives (e.g., Chicago police, the city's police force) in second re... (Source: https://language-guide.cbcrc.ca/home/p/police-forces)
  *Negative Constraints*: avoid abbreviating the names of police forces in national stories (except for well-known initialisms like RCMP, LAPD, NYPD, OPP after first full mention), not CPD in second reference
- **police officer**: The term 'police officer' is acceptable for any rank on a given force. Police in Canada do not follow the military's practice of clearly branding its members as commissioned or non-commissioned officers. (Source: https://language-guide.cbcrc.ca/home/p/police-forces)
  *Negative Constraints*: not policeman or policewoman
- **military police**: Keep 'military police' lowercase unless the words are being used as part of the full, formal name of a unit. Examples of formal names include '18th U.S. Military Police Brigade' and '720th U.S. Military Police Battalion'. (Source: https://language-guide.cbcrc.ca/home/p/police-forces)


### GRAMMAR
- **Verb agreement categories**: The correct verb is debatable when the subject can be viewed as singular or plural. Five broad categories are worth reviewing: Collective nouns, Sports teams and musical groups, Measurements (money, time, weight, etc.), Tricks with 'ics' (ethics, politics, etc.), and Composite themes (tar and feathe... (Source: https://language-guide.cbcrc.ca/home/v/verb-agreement)
- **Couple (plural usage)**: When 'couple' refers to two distinct individuals, use a plural verb and plural pronoun. Example: 'The couple got divorced last year, and they now live in different cities.' (Source: https://language-guide.cbcrc.ca/home/v/verb-agreement)
  *Negative Constraints*: couple it
- **Collective proper nouns (general rule)**: Apply the same approach for certain proper nouns (e.g., 'the Taliban is/are'), keeping in mind that preferences have sometimes been established through convention (e.g., 'the RCMP are' in most cases). (Source: https://language-guide.cbcrc.ca/home/v/verb-agreement)
- **RCMP (plural usage)**: When emphasizing members of the police force, 'RCMP are' is preferred. Example: 'The RCMP are investigating.' (Source: https://language-guide.cbcrc.ca/home/v/verb-agreement)
  *Negative Constraints*: RCMP is
- **RCMP (singular usage)**: When emphasizing the police force itself, 'RCMP has' is preferred. Example: 'The RCMP has a new commissioner.' (Source: https://language-guide.cbcrc.ca/home/v/verb-agreement)
  *Negative Constraints*: RCMP have
- **Plural measurements as a unit**: Plural measurements of money, time, weight, etc., almost always take singular verbs when viewed as a single unit. (Source: https://language-guide.cbcrc.ca/home/v/verb-agreement)
- **Forty dollars**: Example of money as a unit taking a singular verb: 'Forty dollars is missing from her purse.' (Source: https://language-guide.cbcrc.ca/home/v/verb-agreement)
  *Negative Constraints*: Forty dollars are missing
- **That versus which**: Use 'that' when the detail in the sentence is essential, forming a defining or restrictive clause. Use 'which' when the information is simply an aside, forming a non-defining or non-restrictive clause. 'Which' clauses are typically separated by commas and can be removed without changing the overall ... (Source: https://language-guide.cbcrc.ca/home/t/that-versus-which)
  *Negative Constraints*: Do not use commas with 'that' in essential clauses.
- **Verbs (with whom)**: Verbs refer to actions or states. 'Whom' can be the object of a verb. To confirm, substitute 'him' or 'her'. (Source: https://language-guide.cbcrc.ca/home/w/who-versus-whom)

"""